### ISSUE TITLE
Add testcases for OAuth cases.

### ISSUE THREAD

**Issue by dilini-muthumala** [siddhi-io/siddhi-io-http#101]
**Description:**
This issue is created to keep track of the task: Testcases for OAuth cases.

**Related Issues:**
https://github.com/wso2-extensions/siddhi-io-http/pull/100

**Suggested Assignees:**
https://github.com/thushaaanthan

**Comment by mohanvive** [comment]
Added in https://github.com/siddhi-io/siddhi-io-http/pull/103 ..
