### ISSUE TITLE
Connections are not closed correctly in 1.0.44 and 1.0.45 release

### ISSUE THREAD

**Issue by niveathika** [siddhi-io/siddhi-io-http#108]
**Description:**
$subject as https://github.com/wso2-extensions/siddhi-io-http/pull/93 & https://github.com/wso2-extensions/siddhi-io-http/pull/95 fixes was reverted in PR https://github.com/wso2-extensions/siddhi-io-http/pull/102

**Suggested Labels:**
Bug

**Affected Product Version:**
1.0.44, 1.0.45, 1.1.0, 1.1.1

**Related Issues:**
https://github.com/wso2-extensions/siddhi-io-http/issues/92

**Comment by Niveathika92** [comment]
Fixed for 1.1.x from 1.1.2 onwards
