### ISSUE TITLE
Multiple http request sources 

### ISSUE THREAD

**Issue by nprithvi** [siddhi-io/siddhi-io-http#138]
**Description:**
Multiple http request sources in the same file dont allow connection to the second named source (get connection refused). 
-
----
@source(type = 'http', receiver.url = "http://0.0.0.0:8006/ctab",@map(type = 'json'))
define stream CtabUrl (url string);
@source(type='http-request', source.id='StreamSource',  receiver.url='http://0.0.0.0:8007/url', connection.timeout='150000', @map(type='json', @attributes(messageId='trp:messageId')))
define stream UrlStream (messageId string);

---
-----------------

**Affected Product Version:**

Ubuntu

**Comment by mohanvive** [comment]
Works fine in the latest Siddhi distribution. 
Tested with siddhi-tooling-5.1.0-beta ...
