### ISSUE TITLE
Misleading error when backend is not reachable.

### ISSUE THREAD

**Issue by Manasha11** [siddhi-io/siddhi-io-http#175]
**Description:**
In a sink of type 'http-request', if the backend specified in the 'publisher.url' parameter is not reachable, upon simulating an event, the following error is being printed even when a source of  'http-response' is specified to handle responses with 500 status code (using a regex).
```
ERROR {org.wso2.extension.siddhi.io.http.source.HttpResponseMessageListener} - No source of type 'http-response' for status code '500' has been defined. Hence dropping the response message.
```
For the same scenario, from SI 1.0.1 onwards, the correct error is being printed. Following is a sample.
```
ERROR {io.siddhi.core.stream.output.sink.Sink} - Error on 'test_http_status_code'. Dropping event at Sink 'http-request' at 'CreditCardStream' as its still trying to reconnect!, events dropped '{CardNumber=1111}'
```
**Affected Product Version:**
SP 4.3.0, SP 4.4.0, SI 1.0.0

**Steps to reproduce:**
1. Specify an unreachable backend for 'publisher.url' in 'http-request' sink.
2. Make sure a source of type 'http-response' is specified to handle responses with '500' status code, using a regex.
e.g. http.status.code = '[3|4|5]00'
3. Simulate an event.

**Comment by senthuran16** [comment]
Closing since this was addressed in the latest versions.
